name: pefk-dataset
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.13
  - pandas
  - numpy
  - seaborn
  - matplotlib
  - tqdm
  - openpyxl
  - moreutils
  - datasets
  - scikit-learn
  - coloredlogs